nome = input("Digite o seu nome: ")
nome_personagem = input("Digite o nome do seu personagem: ")
classe = input("Digite sua classe: ")

print()
print("================================")
print("   AS CRÔNICAS DA TERRA MÉDIA")
print("================================")
print()
print(f"Bem-vindo, {nome}!")
print()
print(f"Seu personagem é {nome_personagem}")
print(f"Classe escolhida: {classe}")
print()
print("A aventura está prestes a começar...")