nome = input("Nome do personagem: ")
raca = input("Raça: ")
classe = input("Classe: ")
local_de_origem = input("Local de origem: ")
arma = input("Arma principal: ")

print()
print("================================")
print("       FICHA DO AVENTUREIRO")
print("================================")
print()
print("Nome: ", end="")
print(nome)
print(f"Raça: {raca}")
print(f"Classe: {classe}")
print(f"Local de origem: {local_de_origem}")
print(f"Arma principal: {arma}")
print()
print("================================")