nome = input("Nome do aluno: ")
curso = input("Curso: ")
unidade = input("Unidade: ")
turno = input("Turno: ")

print()
print("===== MATRÍCULA =====")
print()
print(f"Aluno: {nome}")
print(f"Curso: {curso}")
print(f"Unidade: {unidade}")
print(f"Turno: {turno}")